import { shutdownManager } from "./shared/shutdown.js";

shutdownManager.initShutdown();
console.log("AgentOS booting (iii-sdk v0.8.0, OTel enabled)");

import "./agent-core.js";
import "./api.js";
import "./approval.js";
import "./approval-tiers.js";
import "./a2a.js";
import "./a2a-cards.js";
import "./browser.js";
import "./code-agent.js";
import "./context-manager.js";
import "./context-monitor.js";
import "./cost-tracker.js";
import "./dashboard.js";
import "./hand-runner.js";
import "./hooks.js";
import "./knowledge-graph.js";
import "./llm-router.js";
import "./loop-guard.js";
import "./mcp-client.js";
import "./memory.js";
import "./migration.js";
import "./model-catalog.js";
import "./rate-limiter.js";
import "./security.js";
import "./security-headers.js";
import "./security-map.js";
import "./security-zeroize.js";
import "./session-replay.js";
import "./skill-security.js";
import "./skillkit-bridge.js";
import "./skills.js";
import "./streaming.js";
import "./swarm.js";
import "./telemetry.js";
import "./tool-profiles.js";
import "./tools.js";
import "./tools-extended.js";
import "./vault.js";
import "./workflow.js";
import "./cron.js";

console.log("AgentOS ready");
