import { init } from "iii-sdk";

const { registerFunction, registerTrigger } = init("ws://localhost:49134", {
  workerName: "model-catalog",
});

type Tier = "frontier" | "smart" | "balanced" | "fast" | "local";

interface ModelEntry {
  id: string;
  provider: string;
  name: string;
  tier: Tier;
  contextWindow: number;
  maxOutput: number;
  inputPrice: number;
  outputPrice: number;
  supportsTools: boolean;
  supportsVision: boolean;
  local: boolean;
}

interface ProviderConfig {
  id: string;
  name: string;
  baseUrl: string;
  envKey: string;
  required: boolean;
  local: boolean;
  driver: "anthropic" | "openai_compat" | "gemini" | "bedrock";
}

const PROVIDERS: ProviderConfig[] = [
  {
    id: "anthropic",
    name: "Anthropic",
    baseUrl: "https://api.anthropic.com",
    envKey: "ANTHROPIC_API_KEY",
    required: true,
    local: false,
    driver: "anthropic",
  },
  {
    id: "openai",
    name: "OpenAI",
    baseUrl: "https://api.openai.com/v1",
    envKey: "OPENAI_API_KEY",
    required: true,
    local: false,
    driver: "openai_compat",
  },
  {
    id: "gemini",
    name: "Google Gemini",
    baseUrl: "https://generativelanguage.googleapis.com",
    envKey: "GEMINI_API_KEY",
    required: true,
    local: false,
    driver: "gemini",
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    baseUrl: "https://api.deepseek.com/v1",
    envKey: "DEEPSEEK_API_KEY",
    required: true,
    local: false,
    driver: "openai_compat",
  },
  {
    id: "groq",
    name: "Groq",
    baseUrl: "https://api.groq.com/openai/v1",
    envKey: "GROQ_API_KEY",
    required: true,
    local: false,
    driver: "openai_compat",
  },
  {
    id: "openrouter",
    name: "OpenRouter",
    baseUrl: "https://openrouter.ai/api/v1",
    envKey: "OPENROUTER_API_KEY",
    required: true,
    local: false,
    driver: "openai_compat",
  },
  {
    id: "mistral",
    name: "Mistral AI",
    baseUrl: "https://api.mistral.ai/v1",
    envKey: "MISTRAL_API_KEY",
    required: true,
    local: false,
    driver: "openai_compat",
  },
  {
    id: "together",
    name: "Together AI",
    baseUrl: "https://api.together.xyz/v1",
    envKey: "TOGETHER_API_KEY",
    required: true,
    local: false,
    driver: "openai_compat",
  },
  {
    id: "fireworks",
    name: "Fireworks AI",
    baseUrl: "https://api.fireworks.ai/inference/v1",
    envKey: "FIREWORKS_API_KEY",
    required: true,
    local: false,
    driver: "openai_compat",
  },
  {
    id: "ollama",
    name: "Ollama",
    baseUrl: "http://localhost:11434/v1",
    envKey: "OLLAMA_API_KEY",
    required: false,
    local: true,
    driver: "openai_compat",
  },
  {
    id: "vllm",
    name: "vLLM",
    baseUrl: "http://localhost:8000/v1",
    envKey: "VLLM_API_KEY",
    required: false,
    local: true,
    driver: "openai_compat",
  },
  {
    id: "lmstudio",
    name: "LM Studio",
    baseUrl: "http://localhost:1234/v1",
    envKey: "LMSTUDIO_API_KEY",
    required: false,
    local: true,
    driver: "openai_compat",
  },
  {
    id: "perplexity",
    name: "Perplexity AI",
    baseUrl: "https://api.perplexity.ai",
    envKey: "PERPLEXITY_API_KEY",
    required: true,
    local: false,
    driver: "openai_compat",
  },
  {
    id: "cohere",
    name: "Cohere",
    baseUrl: "https://api.cohere.ai/v1",
    envKey: "COHERE_API_KEY",
    required: true,
    local: false,
    driver: "openai_compat",
  },
  {
    id: "ai21",
    name: "AI21 Labs",
    baseUrl: "https://api.ai21.com/studio/v1",
    envKey: "AI21_API_KEY",
    required: true,
    local: false,
    driver: "openai_compat",
  },
  {
    id: "cerebras",
    name: "Cerebras",
    baseUrl: "https://api.cerebras.ai/v1",
    envKey: "CEREBRAS_API_KEY",
    required: true,
    local: false,
    driver: "openai_compat",
  },
  {
    id: "sambanova",
    name: "SambaNova",
    baseUrl: "https://api.sambanova.ai/v1",
    envKey: "SAMBANOVA_API_KEY",
    required: true,
    local: false,
    driver: "openai_compat",
  },
  {
    id: "huggingface",
    name: "Hugging Face",
    baseUrl: "https://api-inference.huggingface.co",
    envKey: "HF_API_KEY",
    required: true,
    local: false,
    driver: "openai_compat",
  },
  {
    id: "xai",
    name: "xAI",
    baseUrl: "https://api.x.ai/v1",
    envKey: "XAI_API_KEY",
    required: true,
    local: false,
    driver: "openai_compat",
  },
  {
    id: "replicate",
    name: "Replicate",
    baseUrl: "https://api.replicate.com/v1",
    envKey: "REPLICATE_API_TOKEN",
    required: true,
    local: false,
    driver: "openai_compat",
  },
  {
    id: "github_copilot",
    name: "GitHub Copilot",
    baseUrl: "https://api.githubcopilot.com",
    envKey: "GITHUB_TOKEN",
    required: true,
    local: false,
    driver: "openai_compat",
  },
  {
    id: "qwen",
    name: "Qwen (Alibaba)",
    baseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1",
    envKey: "DASHSCOPE_API_KEY",
    required: true,
    local: false,
    driver: "openai_compat",
  },
  {
    id: "minimax",
    name: "MiniMax",
    baseUrl: "https://api.minimax.chat/v1",
    envKey: "MINIMAX_API_KEY",
    required: true,
    local: false,
    driver: "openai_compat",
  },
  {
    id: "zhipu",
    name: "Zhipu AI (GLM)",
    baseUrl: "https://open.bigmodel.cn/api/paas/v4",
    envKey: "ZHIPU_API_KEY",
    required: true,
    local: false,
    driver: "openai_compat",
  },
  {
    id: "moonshot",
    name: "Moonshot (Kimi)",
    baseUrl: "https://api.moonshot.cn/v1",
    envKey: "MOONSHOT_API_KEY",
    required: true,
    local: false,
    driver: "openai_compat",
  },
  {
    id: "baidu",
    name: "Baidu Qianfan",
    baseUrl: "https://aip.baidubce.com/rpc/2.0",
    envKey: "QIANFAN_API_KEY",
    required: true,
    local: false,
    driver: "openai_compat",
  },
  {
    id: "bedrock",
    name: "AWS Bedrock",
    baseUrl: "https://bedrock-runtime.us-east-1.amazonaws.com",
    envKey: "AWS_ACCESS_KEY_ID",
    required: true,
    local: false,
    driver: "bedrock",
  },
];

const MODELS: ModelEntry[] = [
  {
    id: "claude-opus-4-6",
    provider: "anthropic",
    name: "Claude Opus 4.6",
    tier: "frontier",
    contextWindow: 200000,
    maxOutput: 32000,
    inputPrice: 15,
    outputPrice: 75,
    supportsTools: true,
    supportsVision: true,
    local: false,
  },
  {
    id: "claude-sonnet-4-6",
    provider: "anthropic",
    name: "Claude Sonnet 4.6",
    tier: "smart",
    contextWindow: 200000,
    maxOutput: 16000,
    inputPrice: 3,
    outputPrice: 15,
    supportsTools: true,
    supportsVision: true,
    local: false,
  },
  {
    id: "claude-haiku-4-5",
    provider: "anthropic",
    name: "Claude Haiku 4.5",
    tier: "fast",
    contextWindow: 200000,
    maxOutput: 8192,
    inputPrice: 0.8,
    outputPrice: 4,
    supportsTools: true,
    supportsVision: true,
    local: false,
  },
  {
    id: "gpt-4o",
    provider: "openai",
    name: "GPT-4o",
    tier: "smart",
    contextWindow: 128000,
    maxOutput: 16384,
    inputPrice: 2.5,
    outputPrice: 10,
    supportsTools: true,
    supportsVision: true,
    local: false,
  },
  {
    id: "gpt-4.1",
    provider: "openai",
    name: "GPT-4.1",
    tier: "smart",
    contextWindow: 1000000,
    maxOutput: 32768,
    inputPrice: 2,
    outputPrice: 8,
    supportsTools: true,
    supportsVision: true,
    local: false,
  },
  {
    id: "o3",
    provider: "openai",
    name: "o3",
    tier: "frontier",
    contextWindow: 200000,
    maxOutput: 100000,
    inputPrice: 10,
    outputPrice: 40,
    supportsTools: true,
    supportsVision: true,
    local: false,
  },
  {
    id: "o4-mini",
    provider: "openai",
    name: "o4-mini",
    tier: "balanced",
    contextWindow: 200000,
    maxOutput: 100000,
    inputPrice: 1.1,
    outputPrice: 4.4,
    supportsTools: true,
    supportsVision: true,
    local: false,
  },
  {
    id: "gpt-4o-mini",
    provider: "openai",
    name: "GPT-4o mini",
    tier: "fast",
    contextWindow: 128000,
    maxOutput: 16384,
    inputPrice: 0.15,
    outputPrice: 0.6,
    supportsTools: true,
    supportsVision: true,
    local: false,
  },
  {
    id: "gemini-2.5-flash",
    provider: "gemini",
    name: "Gemini 2.5 Flash",
    tier: "fast",
    contextWindow: 1000000,
    maxOutput: 65536,
    inputPrice: 0.15,
    outputPrice: 0.6,
    supportsTools: true,
    supportsVision: true,
    local: false,
  },
  {
    id: "gemini-2.5-pro",
    provider: "gemini",
    name: "Gemini 2.5 Pro",
    tier: "frontier",
    contextWindow: 1000000,
    maxOutput: 65536,
    inputPrice: 1.25,
    outputPrice: 10,
    supportsTools: true,
    supportsVision: true,
    local: false,
  },
  {
    id: "deepseek-chat",
    provider: "deepseek",
    name: "DeepSeek Chat",
    tier: "balanced",
    contextWindow: 128000,
    maxOutput: 8192,
    inputPrice: 0.14,
    outputPrice: 0.28,
    supportsTools: true,
    supportsVision: false,
    local: false,
  },
  {
    id: "deepseek-reasoner",
    provider: "deepseek",
    name: "DeepSeek Reasoner",
    tier: "smart",
    contextWindow: 128000,
    maxOutput: 8192,
    inputPrice: 0.55,
    outputPrice: 2.19,
    supportsTools: true,
    supportsVision: false,
    local: false,
  },
  {
    id: "llama-3.3-70b",
    provider: "groq",
    name: "Llama 3.3 70B",
    tier: "balanced",
    contextWindow: 131072,
    maxOutput: 32768,
    inputPrice: 0.59,
    outputPrice: 0.79,
    supportsTools: true,
    supportsVision: false,
    local: false,
  },
  {
    id: "grok-2",
    provider: "xai",
    name: "Grok-2",
    tier: "smart",
    contextWindow: 131072,
    maxOutput: 32768,
    inputPrice: 2,
    outputPrice: 10,
    supportsTools: true,
    supportsVision: true,
    local: false,
  },
  {
    id: "grok-3",
    provider: "xai",
    name: "Grok-3",
    tier: "frontier",
    contextWindow: 131072,
    maxOutput: 32768,
    inputPrice: 3,
    outputPrice: 15,
    supportsTools: true,
    supportsVision: true,
    local: false,
  },
  {
    id: "grok-3-mini",
    provider: "xai",
    name: "Grok-3 Mini",
    tier: "fast",
    contextWindow: 131072,
    maxOutput: 32768,
    inputPrice: 0.3,
    outputPrice: 0.5,
    supportsTools: true,
    supportsVision: false,
    local: false,
  },
  {
    id: "mistral-large",
    provider: "mistral",
    name: "Mistral Large",
    tier: "smart",
    contextWindow: 128000,
    maxOutput: 8192,
    inputPrice: 2,
    outputPrice: 6,
    supportsTools: true,
    supportsVision: false,
    local: false,
  },
  {
    id: "sonar-pro",
    provider: "perplexity",
    name: "Sonar Pro",
    tier: "smart",
    contextWindow: 200000,
    maxOutput: 8192,
    inputPrice: 3,
    outputPrice: 15,
    supportsTools: false,
    supportsVision: false,
    local: false,
  },
  {
    id: "sonar",
    provider: "perplexity",
    name: "Sonar",
    tier: "balanced",
    contextWindow: 200000,
    maxOutput: 8192,
    inputPrice: 1,
    outputPrice: 1,
    supportsTools: false,
    supportsVision: false,
    local: false,
  },
  {
    id: "command-a",
    provider: "cohere",
    name: "Command A",
    tier: "smart",
    contextWindow: 256000,
    maxOutput: 8192,
    inputPrice: 2.5,
    outputPrice: 10,
    supportsTools: true,
    supportsVision: false,
    local: false,
  },
  {
    id: "command-r-plus",
    provider: "cohere",
    name: "Command R+",
    tier: "smart",
    contextWindow: 128000,
    maxOutput: 4096,
    inputPrice: 3,
    outputPrice: 15,
    supportsTools: true,
    supportsVision: false,
    local: false,
  },
  {
    id: "command-r",
    provider: "cohere",
    name: "Command R",
    tier: "balanced",
    contextWindow: 128000,
    maxOutput: 4096,
    inputPrice: 0.5,
    outputPrice: 1.5,
    supportsTools: true,
    supportsVision: false,
    local: false,
  },
  {
    id: "jamba-1.5-large",
    provider: "ai21",
    name: "Jamba 1.5 Large",
    tier: "smart",
    contextWindow: 256000,
    maxOutput: 8192,
    inputPrice: 2,
    outputPrice: 8,
    supportsTools: true,
    supportsVision: false,
    local: false,
  },
  {
    id: "jamba-1.5-mini",
    provider: "ai21",
    name: "Jamba 1.5 Mini",
    tier: "fast",
    contextWindow: 256000,
    maxOutput: 8192,
    inputPrice: 0.2,
    outputPrice: 0.4,
    supportsTools: true,
    supportsVision: false,
    local: false,
  },
  {
    id: "cerebras-llama-3.3-70b",
    provider: "cerebras",
    name: "Llama 3.3 70B (Cerebras)",
    tier: "balanced",
    contextWindow: 8192,
    maxOutput: 8192,
    inputPrice: 0.6,
    outputPrice: 0.6,
    supportsTools: true,
    supportsVision: false,
    local: false,
  },
  {
    id: "samba-llama-3.1-405b",
    provider: "sambanova",
    name: "Llama 3.1 405B (SambaNova)",
    tier: "frontier",
    contextWindow: 4096,
    maxOutput: 4096,
    inputPrice: 5,
    outputPrice: 10,
    supportsTools: true,
    supportsVision: false,
    local: false,
  },
  {
    id: "samba-llama-3.3-70b",
    provider: "sambanova",
    name: "Llama 3.3 70B (SambaNova)",
    tier: "balanced",
    contextWindow: 4096,
    maxOutput: 4096,
    inputPrice: 0.6,
    outputPrice: 0.6,
    supportsTools: true,
    supportsVision: false,
    local: false,
  },
  {
    id: "hf-llama-3.3-70b",
    provider: "huggingface",
    name: "Llama 3.3 70B Instruct (HF)",
    tier: "balanced",
    contextWindow: 128000,
    maxOutput: 8192,
    inputPrice: 0.36,
    outputPrice: 0.36,
    supportsTools: true,
    supportsVision: false,
    local: false,
  },
  {
    id: "hf-mistral-7b",
    provider: "huggingface",
    name: "Mistral 7B Instruct v0.3 (HF)",
    tier: "fast",
    contextWindow: 32000,
    maxOutput: 4096,
    inputPrice: 0,
    outputPrice: 0,
    supportsTools: false,
    supportsVision: false,
    local: false,
  },
  {
    id: "replicate-llama-3.3-70b",
    provider: "replicate",
    name: "Llama 3.3 70B Instruct (Replicate)",
    tier: "balanced",
    contextWindow: 128000,
    maxOutput: 8192,
    inputPrice: 0.65,
    outputPrice: 2.75,
    supportsTools: false,
    supportsVision: false,
    local: false,
  },
  {
    id: "qwen-max",
    provider: "qwen",
    name: "Qwen Max",
    tier: "smart",
    contextWindow: 32000,
    maxOutput: 8192,
    inputPrice: 2.4,
    outputPrice: 9.6,
    supportsTools: true,
    supportsVision: false,
    local: false,
  },
  {
    id: "qwen-plus",
    provider: "qwen",
    name: "Qwen Plus",
    tier: "balanced",
    contextWindow: 128000,
    maxOutput: 8192,
    inputPrice: 0.5,
    outputPrice: 1.5,
    supportsTools: true,
    supportsVision: false,
    local: false,
  },
  {
    id: "qwen-turbo",
    provider: "qwen",
    name: "Qwen Turbo",
    tier: "fast",
    contextWindow: 1000000,
    maxOutput: 8192,
    inputPrice: 0.05,
    outputPrice: 0.15,
    supportsTools: true,
    supportsVision: false,
    local: false,
  },
  {
    id: "abab7-chat",
    provider: "minimax",
    name: "ABAB 7 Chat",
    tier: "balanced",
    contextWindow: 245000,
    maxOutput: 8192,
    inputPrice: 1,
    outputPrice: 1,
    supportsTools: true,
    supportsVision: false,
    local: false,
  },
  {
    id: "glm-4-plus",
    provider: "zhipu",
    name: "GLM-4 Plus",
    tier: "smart",
    contextWindow: 128000,
    maxOutput: 8192,
    inputPrice: 7,
    outputPrice: 7,
    supportsTools: true,
    supportsVision: false,
    local: false,
  },
  {
    id: "glm-4",
    provider: "zhipu",
    name: "GLM-4",
    tier: "balanced",
    contextWindow: 128000,
    maxOutput: 8192,
    inputPrice: 1.4,
    outputPrice: 1.4,
    supportsTools: true,
    supportsVision: false,
    local: false,
  },
  {
    id: "moonshot-v1-128k",
    provider: "moonshot",
    name: "Moonshot v1 128K",
    tier: "smart",
    contextWindow: 128000,
    maxOutput: 8192,
    inputPrice: 8.5,
    outputPrice: 8.5,
    supportsTools: true,
    supportsVision: false,
    local: false,
  },
  {
    id: "moonshot-v1-32k",
    provider: "moonshot",
    name: "Moonshot v1 32K",
    tier: "balanced",
    contextWindow: 32000,
    maxOutput: 8192,
    inputPrice: 3.3,
    outputPrice: 3.3,
    supportsTools: true,
    supportsVision: false,
    local: false,
  },
  {
    id: "ernie-4.0-turbo",
    provider: "baidu",
    name: "ERNIE 4.0 Turbo",
    tier: "smart",
    contextWindow: 128000,
    maxOutput: 8192,
    inputPrice: 4.2,
    outputPrice: 8.4,
    supportsTools: true,
    supportsVision: false,
    local: false,
  },
  {
    id: "ernie-3.5-turbo",
    provider: "baidu",
    name: "ERNIE 3.5 Turbo",
    tier: "balanced",
    contextWindow: 128000,
    maxOutput: 8192,
    inputPrice: 0.56,
    outputPrice: 1.12,
    supportsTools: true,
    supportsVision: false,
    local: false,
  },
  {
    id: "bedrock-claude-sonnet",
    provider: "bedrock",
    name: "Claude Sonnet 4 (Bedrock)",
    tier: "smart",
    contextWindow: 200000,
    maxOutput: 8192,
    inputPrice: 3,
    outputPrice: 15,
    supportsTools: true,
    supportsVision: true,
    local: false,
  },
  {
    id: "bedrock-nova-pro",
    provider: "bedrock",
    name: "Amazon Nova Pro (Bedrock)",
    tier: "balanced",
    contextWindow: 300000,
    maxOutput: 8192,
    inputPrice: 0.8,
    outputPrice: 3.2,
    supportsTools: true,
    supportsVision: true,
    local: false,
  },
  {
    id: "bedrock-llama-3.3-70b",
    provider: "bedrock",
    name: "Llama 3.3 70B (Bedrock)",
    tier: "balanced",
    contextWindow: 128000,
    maxOutput: 8192,
    inputPrice: 0.72,
    outputPrice: 0.72,
    supportsTools: true,
    supportsVision: false,
    local: false,
  },
  {
    id: "copilot-gpt-4o",
    provider: "github_copilot",
    name: "GPT-4o (Copilot)",
    tier: "smart",
    contextWindow: 128000,
    maxOutput: 16384,
    inputPrice: 2.5,
    outputPrice: 10,
    supportsTools: true,
    supportsVision: true,
    local: false,
  },
  {
    id: "together-llama-3.3-70b",
    provider: "together",
    name: "Llama 3.3 70B (Together)",
    tier: "balanced",
    contextWindow: 131072,
    maxOutput: 8192,
    inputPrice: 0.88,
    outputPrice: 0.88,
    supportsTools: true,
    supportsVision: false,
    local: false,
  },
  {
    id: "fireworks-llama-3.3-70b",
    provider: "fireworks",
    name: "Llama 3.3 70B (Fireworks)",
    tier: "balanced",
    contextWindow: 131072,
    maxOutput: 8192,
    inputPrice: 0.9,
    outputPrice: 0.9,
    supportsTools: true,
    supportsVision: false,
    local: false,
  },
  {
    id: "openrouter-auto",
    provider: "openrouter",
    name: "OpenRouter Auto",
    tier: "smart",
    contextWindow: 128000,
    maxOutput: 8192,
    inputPrice: 0,
    outputPrice: 0,
    supportsTools: true,
    supportsVision: false,
    local: false,
  },
];

const ALIASES: Record<string, string> = {
  opus: "claude-opus-4-6",
  sonnet: "claude-sonnet-4-6",
  haiku: "claude-haiku-4-5",
  gpt4: "gpt-4o",
  gpt4o: "gpt-4o",
  gpt41: "gpt-4.1",
  o3: "o3",
  o4: "o4-mini",
  flash: "gemini-2.5-flash",
  pro: "gemini-2.5-pro",
  deepseek: "deepseek-chat",
  ds: "deepseek-chat",
  r1: "deepseek-reasoner",
  llama: "llama-3.3-70b",
  grok: "grok-2",
  grok3: "grok-3",
  "grok-3-mini": "grok-3-mini",
  mistral: "mistral-large",
  sonar: "sonar-pro",
  command: "command-a",
  "command-r": "command-r-plus",
  jamba: "jamba-1.5-large",
  cerebras: "cerebras-llama-3.3-70b",
  sambanova: "samba-llama-3.1-405b",
  "llama-3.3": "cerebras-llama-3.3-70b",
  hf: "hf-llama-3.3-70b",
  replicate: "replicate-llama-3.3-70b",
  qwen: "qwen-max",
  minimax: "abab7-chat",
  glm: "glm-4-plus",
  zhipu: "glm-4-plus",
  moonshot: "moonshot-v1-128k",
  kimi: "moonshot-v1-128k",
  ernie: "ernie-4.0-turbo",
  qianfan: "ernie-4.0-turbo",
  bedrock: "bedrock-claude-sonnet",
  nova: "bedrock-nova-pro",
  copilot: "copilot-gpt-4o",
  together: "together-llama-3.3-70b",
  fireworks: "fireworks-llama-3.3-70b",
  openrouter: "openrouter-auto",
  fast: "claude-haiku-4-5",
  cheap: "gpt-4o-mini",
  smart: "claude-sonnet-4-6",
  best: "claude-opus-4-6",
  frontier: "claude-opus-4-6",
};

registerFunction(
  {
    id: "catalog::models",
    description: "List all models with optional filters",
  },
  async ({
    tier,
    provider,
    supportsTools,
  }: { tier?: Tier; provider?: string; supportsTools?: boolean } = {}) => {
    let filtered = [...MODELS];
    if (tier) filtered = filtered.filter((m) => m.tier === tier);
    if (provider) filtered = filtered.filter((m) => m.provider === provider);
    if (supportsTools !== undefined)
      filtered = filtered.filter((m) => m.supportsTools === supportsTools);
    return filtered;
  },
);

registerFunction(
  {
    id: "catalog::resolve",
    description: "Resolve model ID or alias to full model entry",
  },
  async ({ model }: { model: string }) => {
    const resolvedId = ALIASES[model.toLowerCase()] || model;
    const entry = MODELS.find((m) => m.id === resolvedId);
    if (!entry) throw new Error(`Unknown model: ${model}`);
    return entry;
  },
);

registerFunction(
  {
    id: "catalog::providers",
    description: "List all providers with availability",
  },
  async () => {
    return PROVIDERS.map((p) => ({
      ...p,
      available: p.local || !!process.env[p.envKey],
      modelCount: MODELS.filter((m) => m.provider === p.id).length,
    }));
  },
);

registerFunction(
  { id: "catalog::aliases", description: "List all model aliases" },
  async () => ALIASES,
);

registerFunction(
  {
    id: "catalog::provider_test",
    description: "Test if a provider is reachable",
  },
  async ({ providerId }: { providerId: string }) => {
    const provider = PROVIDERS.find((p) => p.id === providerId);
    if (!provider) throw new Error(`Unknown provider: ${providerId}`);

    const apiKey = process.env[provider.envKey];
    if (!apiKey && provider.required) {
      return { reachable: false, reason: `${provider.envKey} not set` };
    }

    const resp = await fetch(provider.baseUrl, {
      method: "HEAD",
      signal: AbortSignal.timeout(5000),
    }).catch(() => null);

    return { reachable: !!resp, status: resp?.status };
  },
);

registerTrigger({
  type: "http",
  function_id: "catalog::models",
  config: { api_path: "api/models", http_method: "GET" },
});
registerTrigger({
  type: "http",
  function_id: "catalog::providers",
  config: { api_path: "api/providers", http_method: "GET" },
});
registerTrigger({
  type: "http",
  function_id: "catalog::aliases",
  config: { api_path: "api/models/aliases", http_method: "GET" },
});
registerTrigger({
  type: "http",
  function_id: "catalog::provider_test",
  config: { api_path: "api/providers/:providerId/test", http_method: "POST" },
});
